accounts/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^change-password/$',
        auth_views.PasswordChangeView.as_view(template_name='accounts/passchange.html',
                                              success_url='done/'),name='pass_change'),
    url(r'^change-password/done/$',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='password_change_done'
        ),
    url('', include('django.contrib.auth.urls'))
]

backend/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/accounts/login/')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^server/', include('server.urls'), name='home'),
    url(r'^files/', include('db_file_storage.urls'))
]

server/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [url(r'upload/(?P<folder_path>.*)$',views.list, name='upload'),
				url(r'^server/media/(?P<path>.+)$',views.download,name='download'),
				 url(r'^register/$',views.register,name='register'),
				 # url(r'^add_folder/$',views.add_folder,name='add_folder'),
				 url(r'^api/files/(?P<folder_path>.*)$', views.api_file_list),
				 url(r'^api/remove_folder/$', views.remove_folder),
				 url(r'^api/remove_file/$', views.remove_file),
				 url(r'^api/upload_folder/$', views.api_upload_folder),
				 url(r'^api/upload_file/$', views.api_upload_file),
				 url(r'^lock/$',views.lock),
				 url(r'^unlock/$',views.unlock),
				 ]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/views.py
from django.contrib.auth import logout, login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

def passchangedone(request):
    logout(request)
    return render(request, 'accounts/passchangedone.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/accounts/login')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

accounts/templates/accounts/a.html
{% extends 'base.html' %}

{% block content %}

<!DOCTYPE html>
{% load static %}
<html>
<head>

  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
body, html {
    height: 100%;
    margin: 0;
}

.bg {
    /* The image used */
    background-image: url("{% static 'images/as.jpg' %}");

    /* Full height */
    height: 100%; 
    link:red

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
.helper{
    height: 400px;
  line-height: 600px;
  text-align: center;
}
/*div {
 height: 400px;
  line-height: 600px;
  text-align: center;
}*/
</style>
</head>
<body class="bg" >
   



<center>    
  <form class="modal-content"  method="post" >
    {% csrf_token %}
    <div class="imgcontainer">
    </div>
    <div class="container">
      <h1>Sign Up</h1>
      <p>Please fill in this form to create an account.</p>
      <hr>
      <label for="{{ form.username.id_for_label }}"><b>Username</b></label>
      {{ form.username }}

      <label for="{{ form.password1.id_for_label }}"><b>Password</b></label>
      {{ form.password1 }}

      <label for="{{ form.password2.id_for_label }}"><b>Repeat Password</b></label>
      {{ form.password2 }}

      <label>
        <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
      </label>

      <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>
      <div class="clearfix">
      <button onclick="location.href='/accounts/login'" type="submit" class="signupbtn" value = "signup" style="width:200px">Sign Up 
      </button>
      <!-- <button onclick="location.href='/accounts/login'" style="width:200px"> Login Redirect</button> -->
    </div>
    </div>
  </form>
  {% endblock %}
<!--   <div class="clearfix">
        <button type="button" onclick="document.getElementById('id02').style.display='none'" class="cancelbtn">Cancel</button>
        
      </div> -->
</div>

</center>
<!-- <script >

var modals = document.getElementById('id02');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target = modals) {
        modals.style.display = "none";
    }
}
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script> -->

</body>

</html>

accounts/templates/accounts/linuxlogin.html
{% if form.errors %}
<p onload=window.location='/accounts/badpage/'>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">

</form>

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: greenyellow;
    color: black;
    padding: 10px 16px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
body, html {
    height: 100%;
    margin: 0;
}

.bg {
    /* The image used */
    background-image: url("{% static 'images/as.jpg' %}");

    /* Full height */
    height: 100%; 

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: repeat;
    background-size: cover;
}
.helper{
    height: 400px;
  line-height: 600px;
  text-align: center;
}
/*div {
 height: 400px;
  line-height: 600px;
  text-align: center;
}*/
</style>
</head>
<body class="bg">
   <script>
function myFunction() {
    alert("Please login with valid credentials");
}
</script>
   <script>
function myFunction1() {
    alert("Please login to see this page.");
}
</script>
<script >
  function myFunction2(){
    alert("Your account doesn't have access to this page. To proceed, please login with an account that has access")
  }
</script>
{% if form.errors %}
<script type="text/javascript"> myFunction(); </script>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <script type="text/javascript"> myFunction2(); </script>
    {% else %}
  <script type="text/javascript"> myFunction1(); </script>
    {% endif %}
{% endif %}

    <center> 
        <div class="helper">
<font size="100" ; height="400px"; line-height="600px"; text-align="center"; vertical-align="middle";><b> Work better, safer, together.                                 </b></font>
</div>
<h1 id="demo" text-align="center" >Secure Cloud simplifies your work,<br> with a central place to share and access files. </h1>
</center>

<center>
    <div>
<button onclick="document.getElementById('id01').style.display='block'" style="width:200px;">Login</button>
<button onclick="location.href='/accounts/signup'" style="width:200px;">Sign Up</button>
</center>
<div>
<div id="id01" class="modal">
  
  <form class="modal-content animate" method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="{% static 'images/img_avatar2.png' %}" alt="Avatar" class="avatar">
    </div>

    <div class="container">
    	<div> 
      <label for="{{ form.username.id_for_label }}"><b>Username</b></label>
      {{ form.username }}
<!--       <input type="text" placeholder="Enter Username" name="uname" required>

 -->
 	</div>
      <label for="{{ form.password.id_for_label }}"><b>Password</b></label>
      <!-- <input type="password" placeholder="Enter Password" name="psw" required>
       -->  
       {{ form.password }}
      
      <button type="submit" value="login"> Login </button>
      <input type="hidden" name="next" value="{{ next }}">
      <label>
        <input type="checkbox" checked="checked" name="remember"> Remember me
      </label>
      <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
    </div>
    </div>
  </form>
  
</div>


<div id="id02" class="modal">
    
  <form id="signup" class="modal-content">
    <div class="imgcontainer">
  <span onclick="document.getElementById('id02').style.display='none'" class="close" title="Close Modal">&times;</span>
    </div>
    <div class="container">
      <h1>Sign Up</h1>
      <p>Please fill in this form to create an account.</p>
      <hr>
      <label for="email"><b>Email</b></label>
      <input type="text" placeholder="Enter Email" name="email" required>

      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>

      <label for="psw-repeat"><b>Repeat Password</b></label>
      <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
      
      <label>
        <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
      </label>

      <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

      <div class="clearfix">
        <button type="button"  >Cancel</button>
        <button type="submit" class="signupbtn">Sign Up</button>
      </div>
    </div>
  </form>
</div>
<script>

 

// Get the modal

// var modals = document.getElementById('id02');

// // When the user clicks anywhere outside of the modal, close it
// window.onclick = function(event) {
//     if (event.target = modals) {
//         modals.style.display = "none";
//     }
// }
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>

</html>

accounts/templates/accounts/passchange.html
{% block content %}

<!DOCTYPE html>
{% load static %}
<html>
<head>

  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: greenyellow;
    color: black;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
body, html {
    height: 100%;
    margin: 0;
}

.bg {
    /* The image used */
    background-image: url("{% static 'images/as.jpg' %}");

    /* Full height */
    height: 100%; 
    link:red

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
.helper{
    height: 400px;
  line-height: 600px;
  text-align: center;
}
/*div {
 height: 400px;
  line-height: 600px;
  text-align: center;
}*/
</style>
</head>
<body class="bg" >
   

     <script>
function myFunction(error) {
    alert(error);
}
</script>
  {% for field in form %}
   {% for error in field.errors %}
        <script > myFunction( '{{error}}' ) </script>
        {% endfor %}
   {% endfor %}


<center>    
  <form class="modal-content"  method="post"  >
    {% csrf_token %}
    <div class="imgcontainer">
    </div>
    <div class="container">
      <h1>Change Password</h1>
      <p>Please fill in this form change your password.</p>
      <hr>
      <label for="{{ form.old_password.id_for_label }}"><b>Old Password</b></label>
      {{ form.old_password }}

      <label for="{{ form.new_password1.id_for_label }}"><b>New Password</b></label>
      {{ form.new_password1 }}

      <label for="{{ form.new_password2.id_for_label }}"><b>Retype New Password</b></label>
      {{ form.new_password2 }}

      <label>
        <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
      </label>

      <div class="clearfix">
      <button  <input type="submit" value="Change my password" class="signupbtn" onclick="location.href='/server/upload'" style="width:200px">Change Password</button>
      <button onclick="location.href='/accounts/login'" style="width:200px"> Login Redirect</button>
    </div>
    </div>
  </form>
  {% endblock %}

</div>

</center>
<script >

var modals = document.getElementById('id02');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target = modals) {
        modals.style.display = "none";
    }
}
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>

</html>

accounts/templates/accounts/passchange1.html
{% block content %}<div id="content-main">

<form action="" method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}"Please correct the error below." {% else %}Please correct the errors below.{% endif %}
    </p>
{% endif %}
woah
<h1>Password change</h1>

<p>Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly.</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    <label for="id_old_password" class="required">Old password:</label>{{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    <label for="id_new_password1" class="required">New password:</label>{{ form.new_password1 }}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    <label for="id_new_password2" class="required">Password (again):</label>{{ form.new_password2 }}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="Change my password" class="default" />
</div>

<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
</div>
</form></div>



{{ user.get_username }}

{% endblock %}

accounts/templates/accounts/passchangedone.html
{% extends 'base.html' %}

{% block content %}

Password changed successfully. Please login again.

{% endblock %}

accounts/templates/accounts/signup1.html
{% extends 'base.html' %}
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit" value="signup">Sign up</button>
  </form>
{% endblock %}